workflows: 
  android-workflow:
    environment:
      flutter: stable 
      groups: 
        - firebase_credentials 
    scripts:
      - name: Set up local.properties
        script: | 
            echo "flutter.sdk=$HOME/programs/flutter" > "hello_world/android/local.properties"
      - name: Installing dependencies
        script: | 
            cd hello_world
            flutter pub get
      - name: Nettoyage de l'environment
        script: |
            cd hello_world
            flutter clean 
      - name: Create debug and test APK
        script: | 
          set -ex
          cd hello_world/android
          ./gradlew app:assembleAndroidTest
          ./gradlew app:assembleDebug 
      - name: Run tests on Firebase Test Lab
        script: |
          echo $GCLOUD_KEY_FILE > ./gcloud_key_file.json
          gcloud auth activate-service-account --key-file=gcloud_key_file.json
          gcloud config set project $FIREBASE_PROJECT

          gcloud firebase test android run \
            --type instrumentation \
            --app hello_world/build/app/outputs/apk/debug/app-debug.apk \
            --test hello_world/build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --device model=Pixel3,version=30 \
            --timeout 3m









